version: "3"
services:
  server:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - backend
    restart: always

  database:
    container_name: database
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: Alfa
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    restart: always

networks:
  backend:
